# Welcome to Jekyll!
remote_theme: arkadianriver/arkadianriver.com

#Social Media
twitter:
  username: Joey
#og_image: https://raw.githubusercontent.com/ErikaVasNormandy/erikavasnormandy.github.io/master/img/tech-bun-transparent%20small.PNG


# Site settings
title: Art of Joseph Richardson
description: Oil Painting By Joey
owner:
  name: Joey # or company name
  url: "https://artofjosephrichardson.com" # your URL
first_published: 2021 # if migrating another site, the year of your first publish
                      # Must be a 4-digit integer year (math is used on it)
#url: "https://artofjosephrichardson.com" # the base hostname & protocol for this site.
#baseurl: "" # the subpath of your site, e.g. /blog
            # Note you'll have to move your robots.txt to the root if you want it used.
            # And list multiple sitemaps if there are other subdirectories you want indexed
            # besides this blog.
lang: en-us # used in HTML lang attributes
#google-analytics: G-8G33H0R5HV

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  # title: What're You Here For?

closing-head: 
closing-para:

# on all pages (and the first three you list display with greeting, if included)
social:
  instagram: https://www.instagram.com/artofjosephr

  github: https://github.com/JMStudiosJoe
#  linkedin-square: https://linkedin.com/in/erika-hudiono
 
  email: /contact/ # you can configure and use this contact page or use your email addy



features-title: Social Medias and Recent Activity

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
# works_in_progress: yes

# Github pages posts future posts by default.
# You'll want to move the user guide posts to _drafts if you set this to true.
future: true
present: true
past: true


custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

empty_array: []

markdown: kramdown
# kramdown:
#   parse_block_html: true
